import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { createDailyTask, deleteDailyTask, getDailyTasks, getSyllabus, startDailyTaskTimer, stopDailyTaskTimer, updateDailyTask, updateDailyTaskStatus } from '../lib/api';
import { addCalendarDays, formatDateOnly, localDateOnly } from '../lib/date-only';
import { dailyTaskStatuses, dailyTaskStatusLabels, dailyTaskTypes, dailyTaskTypeLabels, type CreateDailyTaskInput, type DailyTask, type DailyTaskStatus, type DailyTaskType, type UpdateDailyTaskInput } from '../types/daily-task';
import type { SyllabusData, SyllabusTopic } from '../types/syllabus';

type FormState = { taskDate: string; taskType: DailyTaskType; plannedMinutes: string; actualMinutes: string; subjectId: string; topicId: string; notes: string };
const emptyForm = (date: string): FormState => ({ taskDate: date, taskType: 'THEORY', plannedMinutes: '60', actualMinutes: '', subjectId: '', topicId: '', notes: '' });
function flattenTopics(topics: SyllabusTopic[], prefix = ''): Array<{ id: string; label: string }> { return topics.flatMap((topic) => { const label = prefix ? `${prefix} › ${topic.name}` : topic.name; return [{ id: topic.id, label }, ...flattenTopics(topic.children, label)]; }); }

export function PlanPage() {
  const today = localDateOnly(); const [date, setDate] = useState(today); const [tasks, setTasks] = useState<DailyTask[]>([]); const [syllabus, setSyllabus] = useState<SyllabusData | null>(null); const [state, setState] = useState<'loading'|'ready'|'error'>('loading'); const [form, setForm] = useState<FormState | null>(null); const [editingId, setEditingId] = useState<string | null>(null); const [formError, setFormError] = useState(''); const [saving, setSaving] = useState(false); const [pending, setPending] = useState<Set<string>>(new Set()); const [taskErrors, setTaskErrors] = useState<Record<string,string>>({}); const [deleteId, setDeleteId] = useState<string | null>(null);
  const load = useCallback(async (signal?: AbortSignal) => { setState('loading'); try { setTasks(await getDailyTasks(date, signal)); setState('ready'); } catch { if (!signal?.aborted) setState('error'); } }, [date]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]); useEffect(() => { getSyllabus().then(setSyllabus).catch(() => setSyllabus(null)); }, []);
  const summary = useMemo(() => ({ count: tasks.length, planned: tasks.reduce((sum, task) => sum + task.plannedMinutes, 0), actual: tasks.reduce((sum, task) => sum + (task.actualMinutes ?? 0), 0), done: tasks.filter((task) => task.status === 'DONE').length, skipped: tasks.filter((task) => task.status === 'SKIPPED').length }), [tasks]);
  const replace = (task: DailyTask) => setTasks((current) => task.taskDate === date ? current.map((item) => item.id === task.id ? task : item) : current.filter((item) => item.id !== task.id));
  const run = async (id: string, action: () => Promise<DailyTask>, message: string, recoverCanonicalState = false) => { if (pending.has(id)) return; setPending((current) => new Set(current).add(id)); setTaskErrors((current) => ({ ...current, [id]: '' })); try { replace(await action()); } catch { if (recoverCanonicalState) { try { setTasks(await getDailyTasks(date)); } catch { /* Keep the last known state when recovery is unavailable. */ } } setTaskErrors((current) => ({ ...current, [id]: message })); } finally { setPending((current) => { const next = new Set(current); next.delete(id); return next; }); } };
  const chooseDate = (nextDate: string) => { if (nextDate === date) return; setTasks([]); setState('loading'); setForm(null); setEditingId(null); setDeleteId(null); setDate(nextDate); };
  const openCreate = () => { setEditingId(null); setForm(emptyForm(date)); setFormError(''); };
  const openEdit = (task: DailyTask) => { setEditingId(task.id); setForm({ taskDate: task.taskDate, taskType: task.taskType, plannedMinutes: String(task.plannedMinutes), actualMinutes: task.actualMinutes === null ? '' : String(task.actualMinutes), subjectId: task.subject?.id ?? '', topicId: task.topic?.id ?? '', notes: task.notes ?? '' }); setFormError(''); };
  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (!form || saving) return;
    const planned = Number(form.plannedMinutes);
    const actual = form.actualMinutes === '' ? null : Number(form.actualMinutes);
    const notes = form.notes.trim() || null;
    if (!Number.isInteger(planned) || planned < 1 || planned > 1440 || (actual !== null && (!Number.isInteger(actual) || actual < 0 || actual > 1440)) || form.notes.length > 1000) { setFormError('Check minutes and notes before saving.'); return; }
    const input: CreateDailyTaskInput = { taskDate: form.taskDate, taskType: form.taskType, plannedMinutes: planned, subjectId: form.subjectId || null, topicId: form.topicId || null, notes };
    setSaving(true); setFormError('');
    try {
      if (editingId) {
        const current = tasks.find((task) => task.id === editingId);
        if (!current) throw new Error('Task is no longer available.');
        const changes: UpdateDailyTaskInput = {};
        if (input.taskDate !== current.taskDate) changes.taskDate = input.taskDate;
        if (input.taskType !== current.taskType) changes.taskType = input.taskType;
        if (input.plannedMinutes !== current.plannedMinutes) changes.plannedMinutes = input.plannedMinutes;
        if (input.subjectId !== (current.subject?.id ?? null)) changes.subjectId = input.subjectId;
        if (input.topicId !== (current.topic?.id ?? null)) changes.topicId = input.topicId;
        if (input.notes !== current.notes) changes.notes = input.notes;
        if (actual !== current.actualMinutes) changes.actualMinutes = actual;
        if (Object.keys(changes).length > 0) replace(await updateDailyTask(editingId, changes));
      } else {
        const created = await createDailyTask(input);
        if (created.taskDate === date) setTasks((current) => [...current, created]);
        else chooseDate(created.taskDate);
      }
      setForm(null); setEditingId(null);
    } catch { setFormError(editingId ? 'Couldn’t update task.' : 'Couldn’t add task.'); }
    finally { setSaving(false); }
  };
  const selectedSubject = syllabus?.subjects.find((subject) => subject.id === form?.subjectId); const topicOptions = selectedSubject ? flattenTopics(selectedSubject.topics) : [];
  return <section className="planner" aria-labelledby="plan-title"><header className="planner__header"><div><p className="eyebrow">DAILY PLANNER</p><h1 id="plan-title">Plan</h1></div><button className="primary-button" onClick={openCreate} type="button">+ Add task</button></header>
    <div className="date-nav"><button aria-label="Previous day" onClick={() => chooseDate(addCalendarDays(date,-1))} type="button">←</button><label><span className="sr-only">Selected date</span><input onChange={(event) => chooseDate(event.target.value)} type="date" value={date} /></label><button aria-label="Next day" onClick={() => chooseDate(addCalendarDays(date,1))} type="button">→</button><button className="date-nav__today" disabled={date===today} onClick={() => chooseDate(today)} type="button">Today</button></div>
    <p className="selected-date">{formatDateOnly(date)}</p><p className="daily-summary" data-summary>{summary.count} {summary.count===1?'task':'tasks'} · {summary.planned} min planned · {summary.actual} min actual · {summary.done} done · {summary.skipped} skipped</p>
    {form && <form className="task-form" onSubmit={(event)=>void submit(event)}><div className="task-form__heading"><h2>{editingId?'Edit task':'Add task'}</h2><button aria-label="Close task form" onClick={()=>setForm(null)} type="button">×</button></div><div className="task-form__grid"><label>Task date<input disabled={Boolean(editingId&&tasks.find((task)=>task.id===editingId)?.startedAt)} onChange={(e)=>setForm({...form,taskDate:e.target.value})} required type="date" value={form.taskDate}/></label><label>Task type<select disabled={Boolean(editingId&&tasks.find((task)=>task.id===editingId)?.startedAt)} onChange={(e)=>setForm({...form,taskType:e.target.value as DailyTaskType})} value={form.taskType}>{dailyTaskTypes.map((type)=><option key={type} value={type}>{dailyTaskTypeLabels[type]}</option>)}</select></label><label>Subject<select disabled={Boolean(editingId&&tasks.find((task)=>task.id===editingId)?.startedAt)} onChange={(e)=>setForm({...form,subjectId:e.target.value,topicId:''})} value={form.subjectId}><option value="">No subject</option>{syllabus?.subjects.map((subject)=><option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></label><label>Topic<select disabled={!form.subjectId||Boolean(editingId&&tasks.find((task)=>task.id===editingId)?.startedAt)} onChange={(e)=>setForm({...form,topicId:e.target.value})} value={form.topicId}><option value="">No topic</option>{topicOptions.map((topic)=><option key={topic.id} value={topic.id}>{topic.label}</option>)}</select></label><label>Planned minutes<input max="1440" min="1" onChange={(e)=>setForm({...form,plannedMinutes:e.target.value})} required type="number" value={form.plannedMinutes}/></label>{editingId&&<label>Actual minutes<input disabled={Boolean(tasks.find((task)=>task.id===editingId)?.startedAt)} max="1440" min="0" onChange={(e)=>setForm({...form,actualMinutes:e.target.value})} type="number" value={form.actualMinutes}/></label>}<label className="task-form__notes">Notes<textarea maxLength={1000} onChange={(e)=>setForm({...form,notes:e.target.value})} rows={3} value={form.notes}/></label></div>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="task-form__actions"><button className="primary-button" disabled={saving} type="submit">{saving?'Saving…':editingId?'Save changes':'Add task'}</button><button className="secondary-button" onClick={()=>setForm(null)} type="button">Cancel</button></div></form>}
    {state==='loading'&&<p className="panel-state" role="status">Loading plan…</p>}{state==='error'&&<div className="panel-state" role="alert"><p>Couldn’t load this day’s plan.</p><button className="retry-button" onClick={()=>void load()} type="button">Retry</button></div>}{state==='ready'&&tasks.length===0&&<div className="planner-empty"><p>No tasks planned for this day.</p><button className="secondary-button" onClick={openCreate} type="button">Add task</button></div>}{state==='ready'&&tasks.length>0&&<div className="task-list">{tasks.map((task)=><TaskCard error={taskErrors[task.id]} key={task.id} onDelete={()=>setDeleteId(task.id)} onEdit={()=>openEdit(task)} onStatus={(status)=>void run(task.id,()=>updateDailyTaskStatus(task.id,status),'Couldn’t update task.')} onTimer={()=>void run(task.id,()=>task.startedAt?stopDailyTaskTimer(task.id):startDailyTaskTimer(task.id),task.startedAt?'Couldn’t stop timer.':'Couldn’t start timer.',Boolean(task.startedAt))} pending={pending.has(task.id)} task={task}/>)}</div>}
    {deleteId&&<div className="confirm-backdrop"><div aria-labelledby="delete-title" aria-modal="true" className="confirm-dialog" role="dialog"><h2 id="delete-title">Delete this task?</h2><p>This cannot be undone.</p><div><button autoFocus className="secondary-button" disabled={pending.has(deleteId)} onClick={()=>setDeleteId(null)} type="button">Cancel</button><button className="danger-button" disabled={pending.has(deleteId)} onClick={()=>void(async()=>{const id=deleteId;setPending((c)=>new Set(c).add(id));try{await deleteDailyTask(id);setTasks((c)=>c.filter((t)=>t.id!==id));setDeleteId(null)}catch{setTaskErrors((c)=>({...c,[id]:'Couldn’t delete task.'}));setDeleteId(null)}finally{setPending((c)=>{const n=new Set(c);n.delete(id);return n})}})()} type="button">{pending.has(deleteId)?'Deleting…':'Delete'}</button></div></div></div>}
  </section>;
}

function TaskCard({task,pending,error,onEdit,onDelete,onStatus,onTimer}:{task:DailyTask;pending:boolean;error?:string;onEdit:()=>void;onDelete:()=>void;onStatus:(status:DailyTaskStatus)=>void;onTimer:()=>void}) { return <article className={`task-card task-card--${task.status.toLowerCase()}`} data-task-id={task.id}><div className="task-card__top"><div><p className="task-card__type">{dailyTaskTypeLabels[task.taskType]}</p><h2>{task.topic?.name??task.subject?.name??dailyTaskTypeLabels[task.taskType]}</h2></div><select aria-label={`Status for ${task.topic?.name??dailyTaskTypeLabels[task.taskType]}`} disabled={pending} onChange={(e)=>onStatus(e.target.value as DailyTaskStatus)} value={task.status}>{dailyTaskStatuses.map((status)=><option key={status} value={status}>{dailyTaskStatusLabels[status]}</option>)}</select></div>{task.subject&&<p className="task-card__path">{task.subject.name}{task.topic?` › ${task.topic.name}`:''}</p>}<p className="task-card__minutes">{task.plannedMinutes} min planned · {task.actualMinutes??0} min actual</p>{task.notes&&<p className="task-card__notes">{task.notes}</p>}<div className="task-card__actions"><button className={task.startedAt?'timer-button timer-button--stop':'timer-button'} disabled={pending||task.status!=='TODO'} onClick={onTimer} type="button">{task.startedAt?<><RunningTimer startedAt={task.startedAt}/> · Stop</>:'Start'}</button><button disabled={pending} onClick={onEdit} type="button">Edit</button><button disabled={pending||Boolean(task.startedAt)} onClick={onDelete} title={task.startedAt?'Stop the timer before deleting.':undefined} type="button">Delete</button></div>{error&&<p className="task-error" role="alert">{error}</p>}</article>; }
function RunningTimer({startedAt}:{startedAt:string}) { const [now,setNow]=useState(Date.now()); useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]); const seconds=Math.max(0,Math.floor((now-new Date(startedAt).valueOf())/1000)); return <span aria-label="Timer running">{[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map((part)=>String(part).padStart(2,'0')).join(':')}</span>; }
