import { AnimatePresence, m, useReducedMotionConfig } from 'motion/react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { DelayedPageSkeleton } from '../components/feedback/Loading';
import { getTest, startAttempt } from '../lib/api';
import { motionTokens, nextCountdownFrame, type CountdownFrame } from '../lib/experience';
import type { TestDetail } from '../types/test';

export function TestStartPage(){
  const{testId}=useParams();const navigate=useNavigate();const reduced=useReducedMotionConfig();
  const[test,setTest]=useState<TestDetail|null>(null),[state,setState]=useState<'loading'|'ready'|'error'>('loading'),[starting,setStarting]=useState(false),[error,setError]=useState(''),[frame,setFrame]=useState<CountdownFrame|null>(null);
  const requestSent=useRef(false),timerRef=useRef<number|undefined>(undefined);
  const load=useCallback(async(signal?:AbortSignal)=>{if(!testId){setState('error');return}setState('loading');try{setTest(await getTest(testId,signal));setState('ready')}catch{if(!signal?.aborted)setState('error')}},[testId]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[load]);
  const sendRequest=useCallback(async()=>{if(!testId||requestSent.current)return;requestSent.current=true;setFrame(null);setStarting(true);setError('');try{const attempt=await startAttempt(testId);navigate(`/attempts/${attempt.id}`)}catch{requestSent.current=false;setError('Couldn’t start this test. No attempt was created. Please try again.');setStarting(false)}},[navigate,testId]);
  const cancelCountdown=useCallback(()=>{if(requestSent.current)return;if(timerRef.current)window.clearTimeout(timerRef.current);timerRef.current=undefined;setFrame(null)},[]);
  const begin=()=>{if(test?.activeAttemptId){navigate(`/attempts/${test.activeAttemptId}`);return}if(starting||frame!==null||requestSent.current)return;if(reduced){void sendRequest();return}setFrame(3)};
  useEffect(()=>{if(frame===null)return;const delay=frame==='BEGIN'?180:300;timerRef.current=window.setTimeout(()=>{const next=nextCountdownFrame(frame);if(next===null)void sendRequest();else setFrame(next)},delay);return()=>{if(timerRef.current)window.clearTimeout(timerRef.current)}},[frame,sendRequest]);
  useEffect(()=>{if(frame===null)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')cancelCountdown()};const onVisibility=()=>{if(document.visibilityState==='hidden')cancelCountdown()};document.addEventListener('keydown',onKey);document.addEventListener('visibilitychange',onVisibility);return()=>{document.removeEventListener('keydown',onKey);document.removeEventListener('visibilitychange',onVisibility)}},[cancelCountdown,frame]);
  if(state==='loading')return <section className="test-start"><DelayedPageSkeleton cards={1} label="Loading test" pending/></section>;
  if(state==='error'||!test)return <section className="test-start"><div className="panel-state" role="alert"><h1>Couldn’t load this test</h1><p>Check the local server connection and try again.</p><button className="retry-button" onClick={()=>void load()} type="button">Retry</button><Link to="/test">Back to Tests</Link></div></section>;
  const action=test.activeAttemptId?'Continue Test':test.attemptCount>0?'Retake Test':'Start Test';
  return <section className="test-start" aria-labelledby="test-start-title"><Link className="back-link" to="/test">← Back to Tests</Link><m.article animate={{opacity:1,y:0}} className="test-start__card" initial={{opacity:0,y:8}} transition={{duration:motionTokens.reveal,ease:motionTokens.ease}}><p className="eyebrow">TEST · READY ROOM</p><h1 id="test-start-title">{test.name}</h1><p className="test-start__lead">Settle in. The attempt begins only after you confirm this screen.</p><dl><div><dt>Questions</dt><dd>{test.questionCount}</dd></div><div><dt>Marks</dt><dd>{test.totalMarks}</dd></div><div><dt>Duration</dt><dd>{test.durationMinutes} minutes</dd></div></dl><div className="test-start__notice" role="note"><strong>The timer never pauses.</strong><p>It continues if you refresh, close this page, or exit to Tests. Saved answers remain available when you continue.</p></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary-button test-start__button" disabled={starting} onClick={begin} type="button">{starting?'Opening…':action}</button>{test.activeAttemptId&&<p className="test-start__resume">Your in-progress attempt opens immediately with its original deadline. No countdown is shown.</p>}</m.article><AnimatePresence>{frame!==null&&<m.div animate={{opacity:1}} aria-labelledby="countdown-title" aria-modal="true" className="countdown-overlay" exit={{opacity:0}} initial={{opacity:0}} role="dialog"><div><p id="countdown-title">Focus</p><AnimatePresence mode="wait"><m.strong animate={{opacity:1,scale:1}} aria-live="assertive" exit={{opacity:0,scale:.92}} initial={{opacity:0,scale:.88}} key={frame} transition={{duration:motionTokens.micro,ease:motionTokens.ease}}>{frame}</m.strong></AnimatePresence><button autoFocus onClick={()=>void sendRequest()} type="button">Start now</button><small>Escape cancels before the attempt request is sent.</small></div></m.div>}</AnimatePresence></section>;
}
