import { calculateAttemptTiming } from '../domain/attempt-timing.js';
import { AppError } from '../errors/app-error.js';
import { countAttemptAnswers, createAttemptRow, deleteAttemptRow, findActiveAttempt, findAttemptAnswer, findAttemptAnswers, findAttemptLinks, findAttemptOptions, findAttemptQuestions, findAttemptRefs, findAttemptRow, findAttemptTest, insertAttemptAnswers, submitAttemptRow, updateAttemptAnswer, type AttemptQuestionRow, type AttemptRow, type AttemptTestRow } from '../repositories/attempts.repository.js';
import type { Json, TablesInsert } from '../types/database.types.js';
import type { SaveAttemptAnswer } from '../validation/attempts.schemas.js';

type OptionAnswer = { optionKeys: string[] }; type NumericAnswer = { value: number | null }; type CanonicalAnswer = OptionAnswer | NumericAnswer;
const startQueues = new Map<string, Promise<void>>();
const mutationQueues = new Map<string, Promise<void>>();
function missingAttempt(): never { throw new AppError(404, 'ATTEMPT_NOT_FOUND', 'Attempt was not found.'); }
function emptyAnswer(type: string): CanonicalAnswer { return type === 'NAT' ? { value: null } : { optionKeys: [] }; }
async function serialized<T>(queues: Map<string, Promise<void>>, key: string, work: () => Promise<T>): Promise<T> { const before = queues.get(key) ?? Promise.resolve(); let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const queued = before.catch(() => undefined).then(() => gate); queues.set(key, queued); await before.catch(() => undefined); try { return await work(); } finally { release(); if (queues.get(key) === queued) queues.delete(key); } }
function canonicalize(question: AttemptQuestionRow, options: Array<{ option_key: string; display_order: number }>, answer: SaveAttemptAnswer['submittedAnswer']): CanonicalAnswer {
  if (question.question_type === 'NAT') { if (!('value' in answer) || (answer.value !== null && !Number.isFinite(answer.value))) throw new AppError(400, 'ANSWER_SHAPE_INVALID', 'NAT answers require one finite numeric value or null.'); return { value: answer.value }; }
  if (!('optionKeys' in answer)) throw new AppError(400, 'ANSWER_SHAPE_INVALID', `${question.question_type} answers require optionKeys.`);
  if (new Set(answer.optionKeys).size !== answer.optionKeys.length) throw new AppError(400, 'ANSWER_DUPLICATE_OPTION', 'Answer option keys must be unique.');
  if (question.question_type === 'MCQ' && answer.optionKeys.length > 1) throw new AppError(400, 'ANSWER_SHAPE_INVALID', 'MCQ answers may contain at most one option key.');
  const order = new Map(options.map((option) => [option.option_key, option.display_order]));
  if (answer.optionKeys.some((key) => !order.has(key))) throw new AppError(400, 'ANSWER_OPTION_INVALID', 'The answer contains an option that does not belong to this question.');
  return { optionKeys: [...answer.optionKeys].sort((a, b) => order.get(a)! - order.get(b)!) };
}
async function enforceTiming(row: AttemptRow, test: AttemptTestRow, now = new Date()): Promise<{ row: AttemptRow; timing: ReturnType<typeof calculateAttemptTiming> }> { const timing = calculateAttemptTiming(row.started_at, test.duration_minutes, now); if (row.status === 'IN_PROGRESS' && timing.expired) { await submitAttemptRow(row.id, timing.expiresAt, test.duration_minutes * 60); const submitted = await findAttemptRow(row.id); if (!submitted) missingAttempt(); return { row: submitted, timing }; } return { row, timing }; }
async function loadCore(id: string, now = new Date()) { const found = await findAttemptRow(id); if (!found) missingAttempt(); const test = await findAttemptTest(found.test_id); if (!test) throw new AppError(404, 'TEST_NOT_FOUND', 'Test was not found.'); return { test, ...(await enforceTiming(found, test, now)) }; }
async function mapAttempt(row: AttemptRow, test: AttemptTestRow, timing: ReturnType<typeof calculateAttemptTiming>) { const links = await findAttemptLinks(test.id); const ids = links.map((link) => link.question_id); const [questions, options, answers] = await Promise.all([findAttemptQuestions(ids), findAttemptOptions(ids), findAttemptAnswers(row.id)]); if(questions.length!==links.length||answers.length!==links.length)throw new AppError(409,'ATTEMPT_INVALID','The saved attempt is incomplete.');const questionMap = new Map(questions.map((question) => [question.id, question])); const answerMap = new Map(answers.map((answer) => [answer.question_id, answer])); const refs = await findAttemptRefs([...new Set(questions.map((question) => question.subject_id))], [...new Set(questions.map((question) => question.topic_id))]); const subjects = new Map(refs.subjects.map((item) => [item.id, item])), topics = new Map(refs.topics.map((item) => [item.id, item])); return { id: row.id, status: row.status, startedAt: row.started_at, expiresAt: timing.expiresAt, serverNow: timing.serverNow, submittedAt: row.submitted_at, totalTimeSeconds: row.total_time_seconds, remainingSeconds: row.status === 'SUBMITTED' ? 0 : timing.remainingSeconds, test: { id: test.id, name: test.name, testType: test.test_type, durationMinutes: test.duration_minutes, totalMarks: test.total_marks ?? 0, questionCount: links.length }, questions: links.flatMap((link) => { const question = questionMap.get(link.question_id), answer = answerMap.get(link.question_id); if (!question || !answer) return []; return [{ id: question.id, position: link.position, questionText: question.question_text, questionType: question.question_type, marks: question.marks, subject: subjects.get(question.subject_id) ?? null, topic: topics.get(question.topic_id) ?? null, options: question.question_type === 'NAT' ? [] : options.filter((option) => option.question_id === question.id).map((option) => ({ key: option.option_key, text: option.option_text })), hasImage: Boolean(question.image_path), submittedAnswer: answer.submitted_answer, markedForReview: answer.marked_for_review, timeSeconds: answer.time_seconds }]; }) }; }

export async function startAttempt(testId: string): Promise<{ created: boolean; data: Awaited<ReturnType<typeof mapAttempt>> }> { return serialized(startQueues,testId, async () => { const test = await findAttemptTest(testId); if (!test) throw new AppError(404, 'TEST_NOT_FOUND', 'Test was not found.'); const active = await findActiveAttempt(testId); if (active) { const state = await enforceTiming(active, test); if (state.row.status === 'IN_PROGRESS') return { created: false, data: await mapAttempt(state.row, test, state.timing) }; }
    const links = await findAttemptLinks(testId); if (!links.length) throw new AppError(409, 'TEST_EMPTY', 'A test must contain at least one question before it can be started.'); const questions = await findAttemptQuestions(links.map((link) => link.question_id)); if (questions.length !== links.length) throw new AppError(409, 'TEST_INVALID', 'The saved test question set is incomplete.'); const questionMap = new Map(questions.map((question) => [question.id, question])); let created: AttemptRow | null = null; try { const now = new Date().toISOString(); created = await createAttemptRow({ test_id: testId, status: 'IN_PROGRESS', started_at: now, score: null, submitted_at: null, total_time_seconds: null, updated_at: now }); const rows: TablesInsert<'answers'>[] = links.map((link) => ({ attempt_id: created!.id, question_id: link.question_id, submitted_answer: emptyAnswer(questionMap.get(link.question_id)!.question_type) as Json, is_correct: null, marks_awarded: null, time_seconds: 0, marked_for_review: false, updated_at: now })); await insertAttemptAnswers(rows); if (await countAttemptAnswers(created.id) !== links.length) throw new Error('Attempt answer initialization count mismatch.'); const timing = calculateAttemptTiming(created.started_at, test.duration_minutes); return { created: true, data: await mapAttempt(created, test, timing) }; } catch (error) { if (created) { try { await deleteAttemptRow(created.id); } catch { throw new AppError(500, 'ATTEMPT_CLEANUP_FAILED', 'Attempt creation could not be safely completed.'); } } throw error; }
  }); }
export async function getAttempt(id: string) { const { row, test, timing } = await loadCore(id); return mapAttempt(row, test, timing); }
export async function saveAttemptAnswer(attemptId: string, questionId: string, input: SaveAttemptAnswer) { return serialized(mutationQueues,attemptId,async()=>{
  const { row, test, timing } = await loadCore(attemptId);
  if (row.status !== 'IN_PROGRESS') throw new AppError(409, 'ATTEMPT_SUBMITTED', 'Submitted attempts cannot be changed.');
  const links = await findAttemptLinks(test.id);
  if (!links.some((link) => link.question_id === questionId)) throw new AppError(400, 'QUESTION_NOT_IN_ATTEMPT', 'The question does not belong to this attempt.');
  const question = (await findAttemptQuestions([questionId]))[0];
  if (!question) throw new AppError(404, 'QUESTION_NOT_FOUND', 'Question was not found.');
  const answer = await findAttemptAnswer(attemptId, questionId);
  if (!answer) throw new AppError(409, 'ANSWER_NOT_INITIALIZED', 'The attempt answer row is missing.');
  if (input.timeSeconds < answer.time_seconds) throw new AppError(409, 'ANSWER_TIME_REGRESSION', 'Question time cannot decrease.');
  const durationSeconds = test.duration_minutes * 60;
  if (input.timeSeconds > durationSeconds || input.timeSeconds > timing.boundedTotalSeconds + 2) throw new AppError(400, 'ANSWER_TIME_INVALID', 'Question time exceeds the server-authoritative attempt time.');
  const canonical = canonicalize(question, await findAttemptOptions([questionId]), input.submittedAnswer);
  const saved = await updateAttemptAnswer(answer.id, { submitted_answer: canonical as Json, marked_for_review: input.markedForReview, time_seconds: input.timeSeconds, is_correct: null, marks_awarded: null, updated_at: new Date().toISOString() });
  if (!saved) throw new AppError(409, 'ANSWER_TIME_REGRESSION', 'Question time cannot decrease.');
  const responseTiming = calculateAttemptTiming(row.started_at, test.duration_minutes);
  return { attemptId, questionId, submittedAnswer: saved.submitted_answer, markedForReview: saved.marked_for_review, timeSeconds: saved.time_seconds, savedAt: saved.updated_at, serverNow: responseTiming.serverNow, remainingSeconds: responseTiming.remainingSeconds, status: row.status };
});}
export async function submitAttempt(id: string) { return serialized(mutationQueues,id,async()=>{const core = await loadCore(id); let row = core.row; if (row.status === 'IN_PROGRESS') { row = await submitAttemptRow(id, core.timing.serverNow, core.timing.boundedTotalSeconds) ?? await findAttemptRow(id) ?? missingAttempt(); } const timing = calculateAttemptTiming(row.started_at, core.test.duration_minutes); return mapAttempt(row, core.test, timing);}); }
