import { validateFullMock } from '../domain/full-mock.js';
import { AppError } from '../errors/app-error.js';
import { createTestRow, deleteTestQuestions, deleteTestRow, fetchQuestionReferences, fetchTestStats, findSafeQuestions, findTestQuestions, findTestRow, findTestTopic, insertTestQuestions, listTestRows, testHasAttempts, updateTestRow, type TestQuestionRow, type TestRow } from '../repositories/tests.repository.js';
import type { TablesInsert, TablesUpdate } from '../types/database.types.js';
import type { CreateTest, ListTestsQuery, UpdateTest } from '../validation/tests.schemas.js';

type Definition={name:string;testType:'TOPIC'|'CUSTOM'|'FULL_MOCK';durationMinutes:number;questionIds:string[];topicId:string|undefined};
function summary(row:TestRow,count:number,locked:boolean){return{id:row.id,name:row.name,testType:row.test_type,durationMinutes:row.duration_minutes,totalMarks:row.total_marks??0,questionCount:count,hasAttempts:locked,locked,createdAt:row.created_at,updatedAt:row.updated_at}}
function locked():never{throw new AppError(409,'TEST_LOCKED','This test has attempts and can no longer be edited.')}
function inputs(testId:string,ids:string[]):TablesInsert<'test_questions'>[]{return ids.map((questionId,index)=>({test_id:testId,question_id:questionId,position:index+1}))}
function snapshot(row:TestRow):TablesUpdate<'tests'>{return{name:row.name,test_type:row.test_type,duration_minutes:row.duration_minutes,total_marks:row.total_marks,updated_at:row.updated_at}}
async function validateDefinition(definition:Definition,currentIds:Set<string>){const questions=await findSafeQuestions(definition.questionIds);if(questions.length!==definition.questionIds.length)throw new AppError(404,'QUESTION_NOT_FOUND','One or more selected questions were not found.');const map=new Map(questions.map((question)=>[question.id,question]));const ordered=definition.questionIds.map((id)=>map.get(id)!);if(ordered.some((question)=>question.archived&&!currentIds.has(question.id)))throw new AppError(409,'QUESTION_ARCHIVED','Archived questions cannot be newly selected.');if(definition.testType==='TOPIC'){if(!definition.topicId)throw new AppError(400,'TOPIC_REQUIRED','Select a topic for this test.');if(!await findTestTopic(definition.topicId))throw new AppError(404,'TOPIC_NOT_FOUND','Topic was not found.');if(ordered.some((question)=>question.topic_id!==definition.topicId))throw new AppError(400,'TOPIC_SCOPE_INVALID','Every Topic Test question must belong to the selected topic.')}if((definition.testType==='TOPIC'||definition.testType==='CUSTOM')&&(definition.durationMinutes<1||definition.durationMinutes>600))throw new AppError(400,'DURATION_INVALID','Duration must be between 1 and 600 minutes.');const refs=await fetchQuestionReferences(ordered);const subjects=new Map(refs.subjects.map((subject)=>[subject.id,subject]));if(definition.testType==='FULL_MOCK'){const validation=validateFullMock(ordered.map((question)=>({marks:question.marks,subjectCode:subjects.get(question.subject_id)?.code??''})),definition.durationMinutes);if(!validation.valid)throw new AppError(400,'FULL_MOCK_INVALID',validation.errors.join(' '))}return{ordered,totalMarks:ordered.reduce((sum,question)=>sum+question.marks,0),refs}}
async function detail(row:TestRow,links?:TestQuestionRow[]){const orderedLinks=links??await findTestQuestions(row.id);const questions=await findSafeQuestions(orderedLinks.map((link)=>link.question_id));const questionMap=new Map(questions.map((question)=>[question.id,question]));const refs=await fetchQuestionReferences(questions);const subjects=new Map(refs.subjects.map((value)=>[value.id,value])),topics=new Map(refs.topics.map((value)=>[value.id,value]));const isLocked=await testHasAttempts(row.id);return{...summary(row,orderedLinks.length,isLocked),questions:orderedLinks.flatMap((link)=>{const question=questionMap.get(link.question_id);if(!question)return[];const subject=subjects.get(question.subject_id),topic=topics.get(question.topic_id);return[{id:question.id,position:link.position,questionText:question.question_text,questionType:question.question_type,marks:question.marks,difficulty:question.difficulty,subject:subject?{id:subject.id,code:subject.code,name:subject.name}:null,topic:topic?{id:topic.id,code:topic.code,name:topic.name}:null,hasImage:Boolean(question.image_path),archived:question.archived}]})}}
export async function listTests(query:ListTestsQuery){const result=await listTestRows(query);const stats=await fetchTestStats(result.rows.map((row)=>row.id));return{items:result.rows.map((row)=>summary(row,stats.questionCounts.get(row.id)??0,stats.attempted.has(row.id))),page:query.page,pageSize:query.pageSize,total:result.total,totalPages:Math.ceil(result.total/query.pageSize)}}
export async function getTest(id:string){const row=await findTestRow(id);if(!row)throw new AppError(404,'TEST_NOT_FOUND','Test was not found.');return detail(row)}
export async function createTest(input:CreateTest){const definition:Definition={name:input.name.trim(),testType:input.testType,durationMinutes:input.testType==='FULL_MOCK'?180:input.durationMinutes!,questionIds:input.questionIds,topicId:input.topicId};const valid=await validateDefinition(definition,new Set());let created:TestRow|null=null;try{created=await createTestRow({name:definition.name,test_type:definition.testType,duration_minutes:definition.durationMinutes,total_marks:valid.totalMarks,updated_at:new Date().toISOString()});const links=await insertTestQuestions(inputs(created.id,definition.questionIds));return detail(created,links)}catch(error){if(created){try{await deleteTestRow(created.id);if(await findTestRow(created.id))throw new Error('Cleanup verification failed.')}catch{throw new AppError(500,'TEST_CLEANUP_FAILED','Test creation could not be safely completed.')}}throw error}}
export async function updateTest(id:string,input:UpdateTest){const row=await findTestRow(id);if(!row)throw new AppError(404,'TEST_NOT_FOUND','Test was not found.');if(await testHasAttempts(id))locked();const oldLinks=await findTestQuestions(id);const oldIds=oldLinks.map((link)=>link.question_id);const inferredTopic=(await findSafeQuestions(oldIds))[0]?.topic_id;const testType=(input.testType??row.test_type)as Definition['testType'];const definition:Definition={name:(input.name??row.name).trim(),testType,durationMinutes:testType==='FULL_MOCK'?180:(input.durationMinutes??row.duration_minutes),questionIds:input.questionIds??oldIds,topicId:testType==='TOPIC'?(input.topicId??inferredTopic):undefined};const valid=await validateDefinition(definition,new Set(oldIds));const compositionChanged=definition.questionIds.join(',')!==oldIds.join(',');try{const saved=await updateTestRow(id,{name:definition.name,test_type:definition.testType,duration_minutes:definition.durationMinutes,total_marks:valid.totalMarks,updated_at:new Date().toISOString()});if(!saved)throw new AppError(404,'TEST_NOT_FOUND','Test was not found.');let links=oldLinks;if(compositionChanged){await deleteTestQuestions(id);links=await insertTestQuestions(inputs(id,definition.questionIds))}return detail(saved,links)}catch(error){try{await updateTestRow(id,snapshot(row));await deleteTestQuestions(id);if(oldLinks.length)await insertTestQuestions(oldLinks.map((link)=>({test_id:id,question_id:link.question_id,position:link.position,created_at:link.created_at})))}catch{throw new AppError(500,'TEST_ROLLBACK_FAILED','Test update could not be safely completed.')}throw error}}
export async function removeTest(id:string){const row=await findTestRow(id);if(!row)throw new AppError(404,'TEST_NOT_FOUND','Test was not found.');if(await testHasAttempts(id))locked();await deleteTestRow(id)}
