import { app } from '../app.js';
import { updateTaskRow } from '../repositories/daily-tasks.repository.js';
import { accumulatedActualMinutes } from '../services/daily-tasks.service.js';

type Task = { id: string; taskDate: string; taskType: string; plannedMinutes: number; actualMinutes: number | null; status: string; startedAt: string | null; completedAt: string | null; notes: string | null; planKey: string | null; planSlot: number | null; topic: { path?: string } | null };
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }

async function main(): Promise<void> {
  assert(accumulatedActualMinutes(null, new Date(0), new Date(59_999)) === 0, 'Sub-minute timer rounding failed.');
  assert(accumulatedActualMinutes(null, new Date(0), new Date(60_000)) === 1, 'Exact-minute timer rounding failed.');
  assert(accumulatedActualMinutes(30, new Date(0), new Date(1_249_000)) === 50, 'Timer accumulation/floor failed.');
  let invalidTimerStates = 0; try { accumulatedActualMinutes(0, new Date(1000), new Date(0)); } catch { invalidTimerStates++; } try { accumulatedActualMinutes(1440, new Date(0), new Date(60_000)); } catch { invalidTimerStates++; } assert(invalidTimerStates === 2, 'Timer safety validation failed.');
  const server = app.listen(0, '127.0.0.1'); await new Promise<void>((resolve) => server.once('listening', resolve)); const address = server.address(); assert(address && typeof address !== 'string', 'Server failed to bind.'); const base = `http://127.0.0.1:${address.port}`;
  const request = async (path: string, options?: RequestInit) => { const response = await fetch(`${base}${path}`, { ...options, headers: { 'content-type': 'application/json', ...(options?.headers ?? {}) } }); const payload: unknown = response.status === 204 ? null : await response.json(); return { response, payload }; };
  const date = '2099-12-31'; const createdIds: string[] = [];
  try {
    const initial = await request(`/api/daily-tasks?date=${date}`); assert(initial.response.status === 200 && Array.isArray((initial.payload as { data: Task[] }).data), 'Task list failed.'); const existingIds = new Set((initial.payload as { data: Task[] }).data.map((task) => task.id));
    const syllabus = (await request('/api/syllabus')).payload as { data: { subjects: Array<{ id: string; topics: Array<{ id: string; children: unknown[] }> }> } }; const subjectA = syllabus.data.subjects[0]!; const subjectB = syllabus.data.subjects[1]!; const topicA = subjectA.topics[0]!;
    const invalidRequests = await Promise.all([
      request('/api/daily-tasks?date=bad'), request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'BAD', plannedMinutes: 30 }) }), request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'THEORY', plannedMinutes: 0 }) }), request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'THEORY', plannedMinutes: 1441 }) }), request('/api/daily-tasks/not-a-uuid', { method: 'PATCH', body: JSON.stringify({ notes: 'x' }) }), request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'THEORY', plannedMinutes: 30, topicId: topicA.id }) }), request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'THEORY', plannedMinutes: 30, subjectId: subjectB.id, topicId: topicA.id }) }), request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'THEORY', plannedMinutes: 30, subjectId: '00000000-0000-0000-0000-000000000000' }) }), request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'THEORY', plannedMinutes: 30, extra: true }) }), request('/api/daily-tasks/00000000-0000-0000-0000-000000000000', { method: 'PATCH', body: '{}' })
    ]); const statuses = invalidRequests.map((item) => item.response.status); assert(statuses.every((status) => [400, 404].includes(status)), `Invalid planner request status: ${statuses.join(',')}`);
    const created = await request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'THEORY', plannedMinutes: 30, subjectId: subjectA.id, topicId: topicA.id, notes: 'V1.5 verification task' }) }); assert(created.response.status === 201, 'Create failed.'); let task = (created.payload as { data: Task }).data; createdIds.push(task.id); assert(!existingIds.has(task.id) && task.status === 'TODO' && task.actualMinutes === null && task.planKey === null && task.planSlot === null, 'Create/manual-plan semantics failed.'); assert(typeof task.topic?.path === 'string' && task.topic.path.length > 0, 'Task topic breadcrumb is missing.');
    const listed = (await request(`/api/daily-tasks?date=${date}`)).payload as { data: Task[] }; assert(listed.data.some((item) => item.id === task.id), 'Created task not listed.');
    let updated = await request(`/api/daily-tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ plannedMinutes: 45, notes: 'Updated verification task', actualMinutes: 12 }) }); task = (updated.payload as { data: Task }).data; assert(task.plannedMinutes === 45 && task.actualMinutes === 12 && task.notes === 'Updated verification task', 'Update failed.');
    updated = await request(`/api/daily-tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'DONE' }) }); task = (updated.payload as { data: Task }).data; assert(task.status === 'DONE' && task.completedAt, 'DONE semantics failed.');
    task = ((await request(`/api/daily-tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'TODO' }) })).payload as { data: Task }).data; assert(task.status === 'TODO' && task.completedAt === null && task.actualMinutes === 12, 'Reopen semantics failed.');
    task = ((await request(`/api/daily-tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'SKIPPED' }) })).payload as { data: Task }).data; assert(task.status === 'SKIPPED' && task.completedAt === null, 'SKIPPED semantics failed.');
    task = ((await request(`/api/daily-tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'TODO' }) })).payload as { data: Task }).data;
    const started = await request(`/api/daily-tasks/${task.id}/timer/start`, { method: 'POST' }); task = (started.payload as { data: Task }).data; assert(started.response.status === 200 && task.startedAt, 'Timer start failed.'); assert((await request(`/api/daily-tasks/${task.id}/timer/start`, { method: 'POST' })).response.status === 409, 'Duplicate timer start was not rejected.'); assert((await request(`/api/daily-tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ actualMinutes: 10 }) })).response.status === 409, 'Running actual-minute edit was not rejected.'); assert((await request(`/api/daily-tasks/${task.id}`, { method: 'DELETE' })).response.status === 409, 'Running delete was not rejected.');
    const second = await request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'PRACTICE', plannedMinutes: 20 }) }); const task2 = (second.payload as { data: Task }).data; createdIds.push(task2.id); assert((await request(`/api/daily-tasks/${task2.id}/timer/start`, { method: 'POST' })).response.status === 409, 'Global active-timer rule failed.');
    const stopped = await request(`/api/daily-tasks/${task.id}/timer/stop`, { method: 'POST' }); task = (stopped.payload as { data: Task }).data; assert(stopped.response.status === 200 && task.startedAt === null && (task.actualMinutes ?? 0) >= 12, 'Timer stop failed.'); assert((await request(`/api/daily-tasks/${task.id}/timer/stop`, { method: 'POST' })).response.status === 409, 'Inactive stop was not rejected.');
    const beforeRunawayActual = task.actualMinutes;
    await updateTaskRow(task.id, { started_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() });
    assert((await request(`/api/daily-tasks/${task.id}/timer/stop`, { method: 'POST' })).response.status === 409, 'Runaway timer conflict missing.');
    task = ((await request(`/api/daily-tasks?date=${date}`)).payload as { data: Task[] }).data.find((value) => value.id === task.id)!; assert(task.startedAt === null && task.actualMinutes === beforeRunawayActual, 'Runaway timer did not stop safely.');
    const correctedActual = beforeRunawayActual === 1440 ? 1439 : (beforeRunawayActual ?? 0) + 1;
    task = ((await request(`/api/daily-tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ actualMinutes: correctedActual }) })).payload as { data: Task }).data; assert(task.actualMinutes === correctedActual, 'Runaway timer manual correction failed.');
    const concurrentA = (await request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'MATH', plannedMinutes: 10 }) }).then((result) => (result.payload as { data: Task }).data)); createdIds.push(concurrentA.id);
    const concurrentB = (await request('/api/daily-tasks', { method: 'POST', body: JSON.stringify({ taskDate: date, taskType: 'APTITUDE', plannedMinutes: 10 }) }).then((result) => (result.payload as { data: Task }).data)); createdIds.push(concurrentB.id);
    const concurrentStarts = await Promise.all([request(`/api/daily-tasks/${concurrentA.id}/timer/start`, { method: 'POST' }), request(`/api/daily-tasks/${concurrentB.id}/timer/start`, { method: 'POST' })]);
    assert(concurrentStarts.map((result) => result.response.status).sort().join(',') === '200,409', 'Concurrent global timer exclusion failed.');
    const concurrentWinner = concurrentStarts.find((result) => result.response.status === 200); assert(concurrentWinner, 'Concurrent timer winner missing.'); await request(`/api/daily-tasks/${(concurrentWinner.payload as { data: Task }).data.id}/timer/stop`, { method: 'POST' });
    for (const id of [...createdIds]) { const deletion = await request(`/api/daily-tasks/${id}`, { method: 'DELETE' }); assert(deletion.response.status === 204, 'Delete failed.'); createdIds.splice(createdIds.indexOf(id), 1); }
    const final = (await request(`/api/daily-tasks?date=${date}`)).payload as { data: Task[] }; assert(final.data.every((item) => existingIds.has(item.id)), 'Verification rows remain.');
  } finally {
    let cleanupFailed = false; for (const id of createdIds) { try { await request(`/api/daily-tasks/${id}/timer/stop`, { method: 'POST' }); const deleted = await request(`/api/daily-tasks/${id}`, { method: 'DELETE' }); if (![204, 404].includes(deleted.response.status)) cleanupFailed = true; } catch { cleanupFailed = true; } }
    await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); if (cleanupFailed) throw new Error('Planner verification cleanup failed.');
  }
  console.log(JSON.stringify({ status: 'PASS', invalidRequests: 10, timerLogicCases: 5, runawayRecoveryCases: 1, concurrentStartCases: 1, temporaryRowsRemoved: true, activeTestTimers: 0 }, null, 2));
}
main().catch((error: unknown) => { console.error(`Planner verification failed: ${error instanceof Error ? error.message : 'Unknown error.'}`); process.exitCode = 1; });
