import { app } from '../app.js';
import { backdateAttemptForVerification, countActiveAttempts, countAttemptAnswers, deleteAttemptRow, findAnswerScoringState, findAttemptRow } from '../repositories/attempts.repository.js';
import { deleteQuestionRowForCleanup, findQuestionRow } from '../repositories/questions.repository.js';
import { deleteTestRow, findTestQuestions, findTestRow } from '../repositories/tests.repository.js';
import { removeQuestionImage } from '../services/question-storage.js';

type Result = { response: Response; body: unknown };
type Attempt = { id: string; status: string; startedAt: string; expiresAt: string; submittedAt: string | null; totalTimeSeconds: number | null; questions: Array<{ id: string; questionType: string; submittedAnswer: unknown; markedForReview: boolean; timeSeconds: number; options: Array<{ key: string }> }> };
function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
const data = <T>(result: Result) => (result.body as { data: T }).data;
const json = (body: unknown): RequestInit => ({ headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });
const forbidden = /correctAnswer|correct_answer|explanation|isCorrect|is_correct|marksAwarded|marks_awarded/;
function safe(result: Result, label: string) { assert(!forbidden.test(JSON.stringify(result.body)), `${label} leaked answer-bearing fields.`); }

async function main() {
  const server = app.listen(0, '127.0.0.1'); await new Promise<void>((resolve) => server.once('listening', resolve)); const address = server.address(); assert(address && typeof address !== 'string', 'Server bind failed.'); const base = `http://127.0.0.1:${address.port}`;
  const request = async (path: string, options: RequestInit = {}): Promise<Result> => { const response = await fetch(base + path, options); const body: unknown = response.status === 204 ? null : await response.json(); return { response, body }; };
  const questions: string[] = [], tests: string[] = [], attempts: string[] = []; let baselineTestIds: string[] = [];
  try {
    baselineTestIds = data<{ items: Array<{ id: string }> }>(await request('/api/tests?page=1&pageSize=100')).items.map((item) => item.id).sort();
    const syllabus = data<{ subjects: Array<{ id: string; topics: Array<{ id: string }> }> }>(await request('/api/syllabus')); const scope = syllabus.subjects[0]!;
    const common = { subjectId: scope.id, topicId: scope.topics[0]!.id, marks: 1, difficulty: 'MEDIUM', year: 2026, source: 'Temporary V1.8 verifier', explanation: 'Private verifier explanation' };
    const make = async (body: unknown) => { const result = await request('/api/questions', { method: 'POST', ...json(body) }); assert(result.response.status === 201, 'Verifier question creation failed.'); const id = data<{ id: string }>(result).id; questions.push(id); return id; };
    const mcq = await make({ ...common, questionText: 'Temporary V1.8 MCQ', questionType: 'MCQ', options: [{ key: 'A', text: 'Alpha' }, { key: 'B', text: 'Beta' }], correctAnswer: { optionKeys: ['A'] } });
    const msq = await make({ ...common, questionText: 'Temporary V1.8 MSQ', questionType: 'MSQ', options: [{ key: 'A', text: 'Alpha' }, { key: 'B', text: 'Beta' }, { key: 'C', text: 'Gamma' }], correctAnswer: { optionKeys: ['A', 'C'] } });
    const nat = await make({ ...common, questionText: 'Temporary V1.8 NAT', questionType: 'NAT', options: [], correctAnswer: { min: -2.5, max: 14.75 } });
    const outsider = await make({ ...common, questionText: 'Temporary V1.8 outsider', questionType: 'MCQ', options: [{ key: 'A', text: 'Alpha' }, { key: 'B', text: 'Beta' }], correctAnswer: { optionKeys: ['B'] } });
    const createdTest = await request('/api/tests', { method: 'POST', ...json({ name: 'Temporary V1.8 attempt verifier', testType: 'CUSTOM', durationMinutes: 5, questionIds: [mcq, msq, nat] }) }); assert(createdTest.response.status === 201, 'Verifier test creation failed.'); const testId = data<{ id: string }>(createdTest).id; tests.push(testId); assert((await request(`/api/questions/${nat}`, { method: 'PATCH', ...json({ archived: true }) })).response.status === 200, 'Verifier could not archive a linked question before Start.');
    const starts = await Promise.all(Array.from({ length: 5 }, () => request(`/api/tests/${testId}/attempts`, { method: 'POST' }))); assert(starts[0]!.response.status === 201 && starts.slice(1).every((item) => item.response.status === 200), 'Start/resume status semantics failed.'); starts.forEach((item, index) => safe(item, `Start ${index}`)); const started = data<Attempt>(starts[0]!); attempts.push(started.id); assert(starts.every((item) => data<Attempt>(item).id === started.id), 'Duplicate Start did not return the same attempt.'); assert(started.questions.some((item) => item.id === nat), 'Archived saved question was omitted from Start.'); assert(await countActiveAttempts(testId) === 1, 'Duplicate active attempts were created.'); assert(await countAttemptAnswers(started.id) === 3, 'Initial answer-row count does not match question count.'); const activeSummary=data<{items:Array<{id:string;attemptCount:number;activeAttemptId:string|null;latestAttemptStatus:string|null}>}>(await request('/api/tests?page=1&pageSize=100')).items.find((item)=>item.id===testId);assert(activeSummary?.attemptCount===1&&activeSummary.activeAttemptId===started.id&&activeSummary.latestAttemptStatus==='IN_PROGRESS','Test summary active-attempt metadata failed.');assert((await request(`/api/questions/${nat}`, { method: 'PATCH', ...json({ archived: false }) })).response.status === 200, 'Attempted archived question could not be restored.');
    const initial = await findAnswerScoringState(started.id); assert(initial.length === 3 && initial.every((item) => item.is_correct === null && item.marks_awarded === null && item.time_seconds === 0 && !item.marked_for_review), 'Initial scoring/time/review state is invalid.'); const initialMap = new Map(started.questions.map((item) => [item.questionType, item.submittedAnswer])); assert(JSON.stringify(initialMap.get('MCQ')) === '{"optionKeys":[]}' && JSON.stringify(initialMap.get('MSQ')) === '{"optionKeys":[]}' && JSON.stringify(initialMap.get('NAT')) === '{"value":null}', 'Initial canonical answers are invalid.');
    await backdateAttemptForVerification(started.id, new Date(Date.now() - 120_000).toISOString());
    const save = (questionId: string, submittedAnswer: unknown, markedForReview = false, timeSeconds = 0) => request(`/api/attempts/${started.id}/answers/${questionId}`, { method: 'PUT', ...json({ submittedAnswer, markedForReview, timeSeconds }) });
    for (const answer of [{ optionKeys: [] }, { optionKeys: ['A'] }]) { const result = await save(mcq, answer, false, 0); assert(result.response.status === 200, 'Valid MCQ answer rejected.'); safe(result, 'Save MCQ'); }
    for (const answer of [{ optionKeys: ['A', 'B'] }, { optionKeys: ['Z'] }, { optionKeys: ['A', 'A'] }, { value: 1 }]) assert((await save(mcq, answer)).response.status === 400, 'Invalid MCQ answer accepted.');
    for (const answer of [{ optionKeys: [] }, { optionKeys: ['A'] }, { optionKeys: ['C', 'A'] }]) { const result = await save(msq, answer); assert(result.response.status === 200, 'Valid MSQ answer rejected.'); if ((answer.optionKeys as string[]).length === 2) assert(JSON.stringify(data<{ submittedAnswer: unknown }>(result).submittedAnswer) === '{"optionKeys":["A","C"]}', 'MSQ answer was not canonicalized by display order.'); safe(result, 'Save MSQ'); }
    for (const answer of [{ optionKeys: ['A', 'A'] }, { optionKeys: ['Z'] }, { value: 1 }]) assert((await save(msq, answer)).response.status === 400, 'Invalid MSQ answer accepted.');
    for (const value of [null, 0, -2.5, 14.75]) assert((await save(nat, { value })).response.status === 200, 'Valid NAT answer rejected.'); for (const answer of [{ value: '2' }, { optionKeys: [] }, { value: null, extra: true }, {}]) assert((await save(nat, answer)).response.status === 400, 'Invalid NAT answer accepted.');
    const wrong = await save(outsider, { optionKeys: ['A'] }); assert(wrong.response.status === 400 && await countAttemptAnswers(started.id) === 3, 'Wrong-test question was accepted or inserted.');
    assert((await save(mcq, { optionKeys: [] }, true, 0)).response.status === 200, 'Unanswered + review failed.'); assert((await save(mcq, { optionKeys: ['A'] }, true, 15)).response.status === 200, 'Answered + review failed.'); assert((await save(mcq, { optionKeys: ['A'] }, false, 42)).response.status === 200, 'Answered + no-review failed.'); const regression = await save(mcq, { optionKeys: ['A'] }, false, 20); assert(regression.response.status === 409 && (regression.body as { error: { code: string } }).error.code === 'ANSWER_TIME_REGRESSION', 'Question time regression was not rejected.'); assert((await save(mcq, { optionKeys: [] }, true, 42)).response.status === 200, 'Clear Answer failed.'); const cleared = (await findAnswerScoringState(started.id)).find((item) => item.question_id === mcq)!; assert(JSON.stringify(cleared.submitted_answer) === '{"optionKeys":[]}' && cleared.marked_for_review && cleared.time_seconds === 42, 'Clear did not preserve review/time state.'); assert((await save(mcq, { optionKeys: [] }, false, 42)).response.status === 200, 'Unanswered + no-review failed.'); assert((await save(mcq, { optionKeys: [] }, false, 301)).response.status === 400, 'Question time upper bound failed.');
    const get = await request(`/api/attempts/${started.id}`); assert(get.response.status === 200 && data<Attempt>(get).id === started.id, 'GET Attempt failed.'); safe(get, 'GET Attempt');
    const submittedResult = await request(`/api/attempts/${started.id}/submit`, { method: 'POST' }); assert(submittedResult.response.status === 200, 'Submit failed.'); safe(submittedResult, 'Submit'); const submitted = data<Attempt>(submittedResult); assert(submitted.status === 'SUBMITTED' && submitted.submittedAt && submitted.totalTimeSeconds !== null, 'Submitted timing state is invalid.'); const submittedAt = submitted.submittedAt; const persisted = await findAnswerScoringState(started.id); assert(persisted.every((item) => item.is_correct === null && item.marks_awarded === null), 'Submit populated future scoring fields.'); assert((await findAttemptRow(started.id))?.score === null, 'Submit populated attempt score.'); const afterSubmit = await save(mcq, { optionKeys: ['A'] }, false, 42); assert(afterSubmit.response.status === 409 && (afterSubmit.body as { error: { code: string } }).error.code === 'ATTEMPT_SUBMITTED', 'Post-submit mutation was accepted.'); const submitAgain = data<Attempt>(await request(`/api/attempts/${started.id}/submit`, { method: 'POST' })); assert(submitAgain.submittedAt === submittedAt, 'Idempotent submit reset submittedAt.');
    const submittedSummary=data<{items:Array<{id:string;attemptCount:number;activeAttemptId:string|null;latestAttemptStatus:string|null}>}>(await request('/api/tests?page=1&pageSize=100')).items.find((item)=>item.id===testId);assert(submittedSummary?.attemptCount===1&&submittedSummary.activeAttemptId===null&&submittedSummary.latestAttemptStatus==='SUBMITTED','Test summary Retake metadata failed.');
    const retakeResult = await request(`/api/tests/${testId}/attempts`, { method: 'POST' }); assert(retakeResult.response.status === 201, 'Retake was not created.'); const retake = data<Attempt>(retakeResult); attempts.push(retake.id); assert(retake.id !== started.id && retake.status === 'IN_PROGRESS' && retake.questions.every((item) => item.timeSeconds === 0 && !item.markedForReview && JSON.stringify(item.submittedAnswer) === JSON.stringify(item.questionType === 'NAT' ? { value: null } : { optionKeys: [] })), 'Retake did not start fresh.');
    await backdateAttemptForVerification(retake.id, new Date(Date.now() - 360_000).toISOString()); const expiredResult = await request(`/api/attempts/${retake.id}`); const expired = data<Attempt>(expiredResult); const expiredRow = await findAttemptRow(retake.id); assert(expired.status === 'SUBMITTED' && expired.totalTimeSeconds === 300 && Date.parse(expired.submittedAt ?? '') === Date.parse(expired.expiresAt) && expiredRow?.score === null, `Lazy expiry finalization failed: ${JSON.stringify({ status: expired.status, totalTimeSeconds: expired.totalTimeSeconds, submittedAt: expired.submittedAt, expiresAt: expired.expiresAt, score: expiredRow?.score })}`); const expiredSave = await request(`/api/attempts/${retake.id}/answers/${mcq}`, { method: 'PUT', ...json({ submittedAnswer: { optionKeys: ['A'] }, markedForReview: false, timeSeconds: 0 }) }); assert(expiredSave.response.status === 409, 'Expired attempt accepted an answer mutation.');
  } finally {
    let cleanupFailed = false;
    for (const id of attempts) try { await deleteAttemptRow(id); } catch { cleanupFailed = true; }
    for (const id of tests) try { await deleteTestRow(id); } catch { cleanupFailed = true; }
    for (const id of questions) try { await removeQuestionImage(id); await deleteQuestionRowForCleanup(id); } catch { cleanupFailed = true; }
    for (const id of attempts) if (await findAttemptRow(id)) cleanupFailed = true;
    for (const id of tests) if (await findTestRow(id) || (await findTestQuestions(id)).length) cleanupFailed = true;
    for (const id of questions) if (await findQuestionRow(id)) cleanupFailed = true;
    const after = data<{ items: Array<{ id: string }> }>(await request('/api/tests?page=1&pageSize=100')).items.map((item) => item.id).sort(); if (after.join(',') !== baselineTestIds.join(',')) cleanupFailed = true;
    await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); if (cleanupFailed) throw new Error('Attempt verifier cleanup failed.');
  }
  console.log(JSON.stringify({ status: 'PASS', startResume: true, duplicateActiveAttempts: 0, answerRowsInitialized: 3, answerTypes: ['MCQ', 'MSQ', 'NAT'], reviewStates: 4, timeMonotonic: true, safePayloadLeakage: 0, scoringMutations: 0, submitIdempotent: true, retakeFresh: true, expiryEnforced: true, temporaryAttemptsRemoved: true, temporaryAnswersRemoved: true, temporaryTestsRemoved: true, temporaryTestQuestionsRemoved: true, temporaryQuestionsRemoved: true, temporaryOptionsRemoved: true, permanentMutations: 0 }, null, 2));
}
main().catch((error: unknown) => { console.error(`Attempt verification failed: ${error instanceof Error ? error.message : 'Unknown error.'}`); process.exit(1); });
