import { randomUUID } from 'node:crypto';
import { app } from '../app.js';
import { validateFullMock, engineeringMathematicsSubjectCode, generalAptitudeSubjectCode, type FullMockQuestion } from '../domain/full-mock.js';
import { deleteQuestionRowForCleanup, findQuestionRow } from '../repositories/questions.repository.js';
import { deleteVerifierAttempt, findTestQuestions, findTestRow, findVerifierAttempt, insertVerifierAttempt } from '../repositories/tests.repository.js';
import { removeQuestionImage } from '../services/question-storage.js';

type Result={response:Response;body:unknown}; type Detail={id:string;name:string;testType:string;durationMinutes:number;totalMarks:number;questionCount:number;locked:boolean;questions:Array<{id:string;position:number;archived:boolean}>};
function assert(value:unknown,message:string):asserts value{if(!value)throw new Error(message)}const json=(body:unknown):RequestInit=>({headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=<T>(result:Result)=>(result.body as{data:T}).data;
const repeated=(count:number,marks:number,subjectCode:string):FullMockQuestion[]=>Array.from({length:count},()=>({marks,subjectCode}));
function verifyFullMockDomain(){const valid=[...repeated(5,1,generalAptitudeSubjectCode),...repeated(5,2,generalAptitudeSubjectCode),...repeated(1,1,engineeringMathematicsSubjectCode),...repeated(6,2,engineeringMathematicsSubjectCode),...repeated(24,1,'CS-S2-DIGITAL-LOGIC'),...repeated(24,2,'CS-S9-COMPUTER-NETWORKS')];const result=validateFullMock(valid,180);assert(result.valid&&result.totalQuestions===65&&result.totalMarks===100&&result.gaQuestions===10&&result.gaMarks===15&&result.nonGaQuestions===55&&result.nonGaMarks===85&&result.engineeringMathMarks===13&&result.coreCsMarks===72,'Valid Full Mock fixture failed.');assert(validateFullMock(valid,179).errors.some((error)=>error.includes('180')),'Duration rule failed.');assert(validateFullMock(valid.slice(1),180).errors.some((error)=>error.includes('65 questions')),'Question-count rule failed.');const gaCount=valid.map((q,i)=>i===0?{...q,subjectCode:'CS-S2-DIGITAL-LOGIC'}:q);assert(validateFullMock(gaCount,180).errors.some((error)=>error.includes('10 questions')),'GA count rule failed.');const gaMarks=valid.map((q,i)=>i===0?{...q,marks:2}:i===20?{...q,marks:1}:q);assert(validateFullMock(gaMarks,180).errors.some((error)=>error.includes('15 marks')),'GA marks rule failed.');const math=valid.map((q,i)=>i===10?{...q,subjectCode:'CS-S2-DIGITAL-LOGIC'}:q);assert(validateFullMock(math,180).errors.some((error)=>error.includes('13 marks')),'Math rule failed.');const alternateCore=valid.map((q)=>q.subjectCode.startsWith('CS-S9')?{...q,subjectCode:'CS-S4-PROGRAMMING-DATA-STRUCTURES'}:q);assert(validateFullMock(alternateCore,180).valid,'An arbitrary core-subject count was invented.')}

async function main(){verifyFullMockDomain();const server=app.listen(0,'127.0.0.1');await new Promise<void>((resolve)=>server.once('listening',resolve));const address=server.address();assert(address&&typeof address!=='string','Server bind failed.');const base=`http://127.0.0.1:${address.port}`;const request=async(path:string,options:RequestInit={}):Promise<Result>=>{const response=await fetch(base+path,options);const body:unknown=response.status===204?null:await response.json();return{response,body}};const createdQuestions:string[]=[],createdTests:string[]=[],attempts:string[]=[];let baselineIds:string[]=[];
try{const baseline=data<{items:Array<{id:string}>}>(await request('/api/tests?page=1&pageSize=100'));baselineIds=baseline.items.map((item)=>item.id).sort();assert((await request('/api/tests?page=0')).response.status===400&&(await request('/api/tests?pageSize=101')).response.status===400&&(await request('/api/tests?testType=BAD')).response.status===400,'Invalid list query accepted.');assert((await request('/api/tests/not-a-uuid')).response.status===400,'Invalid test UUID accepted.');
const syllabus=data<{subjects:Array<{id:string;topics:Array<{id:string}>}>}>(await request('/api/syllabus'));const first=syllabus.subjects[0]!,second=syllabus.subjects[1]!;const question=(subjectId:string,topicId:string,text:string,marks:1|2)=>({subjectId,topicId,questionText:text,questionType:'MCQ',marks,difficulty:'MEDIUM',year:2026,source:'V1.7 verifier',explanation:null,options:[{key:'A',text:'One'},{key:'B',text:'Two'}],correctAnswer:{optionKeys:['A']}});const q1=data<{id:string}>(await request('/api/questions',{method:'POST',...json(question(first.id,first.topics[0]!.id,'Temporary V1.7 verifier A',1))}));createdQuestions.push(q1.id);const q2=data<{id:string}>(await request('/api/questions',{method:'POST',...json(question(second.id,second.topics[0]!.id,'Temporary V1.7 verifier B',2))}));createdQuestions.push(q2.id);
const baseTest={name:'Temporary V1.7 custom',testType:'CUSTOM',durationMinutes:30,questionIds:[q1.id,q2.id]};const invalidBodies=[{...baseTest,name:' '},{...baseTest,name:'x'.repeat(201)},{...baseTest,testType:'BAD'},{...baseTest,durationMinutes:0},{...baseTest,durationMinutes:601},{...baseTest,questionIds:[]},{...baseTest,questionIds:[q1.id,q1.id]},{...baseTest,questionIds:['bad']},{...baseTest,questionIds:[randomUUID()]},{...baseTest,questionIds:Array.from({length:101},()=>randomUUID())},{...baseTest,totalMarks:3},{...baseTest,unknown:true},{...baseTest,testType:'FULL_MOCK',durationMinutes:179}];for(const body of invalidBodies){const result=await request('/api/tests',{method:'POST',...json(body)});assert([400,404].includes(result.response.status),'Invalid test body accepted.')}assert((await request('/api/tests/'+randomUUID(),{method:'PATCH',...json({})})).response.status===400,'Empty PATCH accepted.');
const wrongTopic=await request('/api/tests',{method:'POST',...json({name:'Wrong topic',testType:'TOPIC',durationMinutes:20,topicId:first.topics[0]!.id,questionIds:[q2.id]})});assert(wrongTopic.response.status===400,'Wrong-topic question accepted.');assert((await request('/api/tests',{method:'POST',...json({name:'Unknown topic',testType:'TOPIC',durationMinutes:20,topicId:randomUUID(),questionIds:[q1.id]})})).response.status===404,'Unknown Topic scope accepted.');await request(`/api/questions/${q2.id}`,{method:'PATCH',...json({archived:true})});assert((await request('/api/tests',{method:'POST',...json({...baseTest,questionIds:[q2.id]})})).response.status===409,'Archived question newly selected.');await request(`/api/questions/${q2.id}`,{method:'PATCH',...json({archived:false})});
let topic=data<Detail>(await request('/api/tests',{method:'POST',...json({name:'Temporary topic',testType:'TOPIC',durationMinutes:20,topicId:first.topics[0]!.id,questionIds:[q1.id]})}));createdTests.push(topic.id);assert(topic.totalMarks===1&&topic.questions[0]?.position===1,'Topic test marks/order failed.');assert((await request(`/api/questions/${q2.id}`,{method:'PATCH',...json({questionText:'Temporary unlocked V1.7 verifier edit'})})).response.status===200,'An unlocked referenced question could not be edited.');
let custom=data<Detail>(await request('/api/tests',{method:'POST',...json(baseTest)}));createdTests.push(custom.id);assert(custom.totalMarks===3&&custom.questionCount===2&&custom.questions.map((item)=>item.id).join(',')===`${q1.id},${q2.id}`,'Custom create/order/marks failed.');const filtered=data<{items:Array<{id:string;locked:boolean}>}>(await request('/api/tests?testType=CUSTOM'));assert(filtered.items.some((item)=>item.id===custom.id),'Test type filter failed.');assert(!/correctAnswer|correct_answer|explanation|isCorrect/.test(JSON.stringify(filtered))&&!/correctAnswer|correct_answer|explanation|isCorrect/.test(JSON.stringify(custom)),'Test API leaked answer data.');
custom=data<Detail>(await request(`/api/tests/${custom.id}`,{method:'PATCH',...json({name:'Edited temporary V1.7 custom',durationMinutes:45,questionIds:[q2.id,q1.id]})}));assert(custom.name.startsWith('Edited')&&custom.durationMinutes===45&&custom.totalMarks===3&&custom.questions.map((item)=>`${item.position}:${item.id}`).join(',')===`1:${q2.id},2:${q1.id}`,'Custom edit/order persistence failed.');custom=data<Detail>(await request(`/api/tests/${custom.id}`));assert(custom.questions[0]?.id===q2.id&&custom.questions[1]?.id===q1.id,'GET detail order failed.');
await request(`/api/questions/${q1.id}`,{method:'PATCH',...json({archived:true})});assert(data<Detail>(await request(`/api/tests/${custom.id}`)).questions.some((item)=>item.id===q1.id&&item.archived),'Archived linked question became unreadable.');assert((await request(`/api/tests/${custom.id}`,{method:'PATCH',...json({name:'Archived link retained'})})).response.status===200,'Existing archived link could not remain.');await request(`/api/questions/${q1.id}`,{method:'PATCH',...json({archived:false})});
const attempt=await insertVerifierAttempt(custom.id);attempts.push(attempt);const lockedList=data<{items:Array<{id:string;locked:boolean}>}>(await request('/api/tests?testType=CUSTOM'));assert(lockedList.items.some((item)=>item.id===custom.id&&item.locked),'Locked summary state missing.');const lockedPatch=await request(`/api/tests/${custom.id}`,{method:'PATCH',...json({name:'Forbidden'})}),lockedDelete=await request(`/api/tests/${custom.id}`,{method:'DELETE'});assert(lockedPatch.response.status===409&&(lockedPatch.body as{error:{code:string}}).error.code==='TEST_LOCKED'&&lockedDelete.response.status===409,'Test lock failed.');const questionLock=await request(`/api/questions/${q1.id}`,{method:'PATCH',...json({questionText:'Forbidden'})});assert(questionLock.response.status===409&&(questionLock.body as{error:{code:string}}).error.code==='QUESTION_LOCKED_BY_ATTEMPT','Question content lock failed.');assert((await request(`/api/questions/${q1.id}/image`,{method:'PUT',headers:{'content-type':'image/png'},body:Buffer.from('89504e470d0a1a0a','hex')})).response.status===409,'Locked image replacement accepted.');assert((await request(`/api/questions/${q1.id}/image`,{method:'DELETE'})).response.status===409,'Locked image removal accepted.');assert((await request(`/api/questions/${q1.id}`,{method:'PATCH',...json({archived:true})})).response.status===200&&(await request(`/api/questions/${q1.id}`,{method:'PATCH',...json({archived:false})})).response.status===200,'Locked question archive policy failed.');
await deleteVerifierAttempt(attempt);attempts.splice(attempts.indexOf(attempt),1);await request(`/api/tests/${custom.id}`,{method:'DELETE'});createdTests.splice(createdTests.indexOf(custom.id),1);assert((await request(`/api/tests/${custom.id}`)).response.status===404,'Deleted test remained.');await request(`/api/tests/${topic.id}`,{method:'DELETE'});createdTests.splice(createdTests.indexOf(topic.id),1);
}finally{let cleanupFailed=false;for(const attempt of attempts){try{await deleteVerifierAttempt(attempt)}catch{cleanupFailed=true}}for(const id of createdTests){try{if(await findTestRow(id)){if(await findTestQuestions(id))await (await import('../repositories/tests.repository.js')).deleteTestRow(id)}}catch{cleanupFailed=true}}for(const id of createdQuestions){try{await removeQuestionImage(id);await deleteQuestionRowForCleanup(id)}catch{cleanupFailed=true}}for(const id of attempts)if(await findVerifierAttempt(id))cleanupFailed=true;for(const id of createdTests)if(await findTestRow(id)||(await findTestQuestions(id)).length)cleanupFailed=true;for(const id of createdQuestions)if(await findQuestionRow(id))cleanupFailed=true;const after=data<{items:Array<{id:string}>}>(await request('/api/tests?page=1&pageSize=100'));if(after.items.map((item)=>item.id).sort().join(',')!==baselineIds.join(','))cleanupFailed=true;await new Promise<void>((resolve,reject)=>server.close((error)=>error?reject(error):resolve()));if(cleanupFailed)throw new Error('Test verifier cleanup failed.')}
console.log(JSON.stringify({status:'PASS',testTypes:['TOPIC','CUSTOM','FULL_MOCK'],fullMockDomainCases:7,invalidRequestCases:19,answerLeakage:0,lockedPatch:true,lockedDelete:true,questionLock:true,unlockedQuestionEdit:true,archiveWhileLocked:true,temporaryTestsRemoved:true,temporaryTestQuestionsRemoved:true,temporaryAttemptsRemoved:true,temporaryQuestionsRemoved:true,permanentMutations:0},null,2))}
main().catch((error:unknown)=>{console.error(`Test verification failed: ${error instanceof Error?error.message:'Unknown error.'}`);process.exit(1)});
